# Generated by Django 6.0.2 on 2026-02-15 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FilmCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('duration', models.PositiveIntegerField()),
                ('age_control', models.PositiveIntegerField()),
                ('display', models.CharField(choices=[('on_display', 'Em Cartaz'), ('shortly', 'Em Breve')], default='on_display')),
                ('thumb_url', models.URLField()),
                ('ticket_url', models.URLField()),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ManyToManyField(related_name='films', to='api.category')),
            ],
        ),
    ]
