# Generated by Django 6.0.2 on 2026-02-19 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgeRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_rating', models.CharField(choices=[('livre', 'Livre'), ('10', '10 Anos'), ('12', '12 Anos'), ('14', '14 Anos'), ('16', '16 Anos'), ('18', '18 Anos')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FilmCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('duration', models.PositiveIntegerField()),
                ('display', models.CharField(choices=[('on_display', 'Em Cartaz'), ('shortly', 'Em Breve')], default='on_display')),
                ('thumb_image', models.FileField(upload_to='thumbs/')),
                ('ticket_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('age_rating_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.agerating')),
                ('category', models.ManyToManyField(related_name='films', to='api.category')),
            ],
        ),
    ]
