# Generated by Django 6.0.2 on 2026-02-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FilmCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('duration', models.PositiveIntegerField()),
                ('age_rating', models.CharField(choices=[('livre', 'Livre'), ('10', '10 Anos'), ('12', '12 Anos'), ('14', '14 Anos'), ('16', '16 Anos'), ('18', '18 Anos')], default='livre')),
                ('display', models.CharField(choices=[('on_display', 'Em Cartaz'), ('shortly', 'Em Breve')], default='on_display')),
                ('thumb_image', models.FileField(upload_to='thumbs/')),
                ('ticket_url', models.URLField()),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('days_list', models.JSONField(default=list)),
                ('room', models.CharField(max_length=100)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
