# Generated by Django 6.0.2 on 2026-02-23 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mod_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categorytype',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mod_types', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='api.categorytype'),
        ),
        migrations.AddField(
            model_name='filmcard',
            name='category',
            field=models.ManyToManyField(related_name='films', to='api.category'),
        ),
        migrations.AddField(
            model_name='filmcard',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mod_films', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='session',
            name='film',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session_film', to='api.filmcard'),
        ),
        migrations.AddField(
            model_name='session',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
