# Generated by Django 6.0.2 on 2026-02-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmcard',
            name='age_rating_id',
        ),
        migrations.AddField(
            model_name='filmcard',
            name='age_rating',
            field=models.CharField(choices=[('livre', 'Livre'), ('10', '10 Anos'), ('12', '12 Anos'), ('14', '14 Anos'), ('16', '16 Anos'), ('18', '18 Anos')], default='livre'),
        ),
        migrations.DeleteModel(
            name='AgeRating',
        ),
    ]
