# Generated by Django 6.0.2 on 2026-03-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='day_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
