# Generated by Django 6.0.2 on 2026-02-21 23:09

from django.db import migrations


def insert_versions(apps, schema_editor):
    Version = apps.get_model('api', 'Version')

    versions = [
        "Dublado",
        "Legendado",
        "Nacional (Português)",
        "Original",
        "Voz Original com Legenda",
        "2D",
        "3D",
        "IMAX",
        "4DX",
        "MX4D",
        "ScreenX",
        "VIP",
        "Premium",
        "Dolby Cinema",
        "XD (Extreme Digital Cinema)",
        "Dolby Digital",
        "Dolby Atmos",
        "DTS",
        "DTS:X",
        "7.1 Surround",
        "5.1 Surround"
    ]

    for name in versions:
        Version.objects.get_or_create(name=name)


def insert_categories(apps, schema_editor):
    Category = apps.get_model('api', 'Category')

    categories = [
        "Ação",
        "Aventura",
        "Animação",
        "Biografia",
        "Catástrofe",
        "Cinema de Arte",
        "Comédia",
        "Comédia Romântica",
        "Comédia Dramática",
        "Crime",
        "Cult",
        "Documentário",
        "Drama",
        "Drama Histórico",
        "Drama Romântico",
        "Espionagem",
        "Fantasia",
        "Faroeste (Western)",
        "Ficção Científica",
        "Guerra",
        "Histórico",
        "Infantil",
        "Mistério",
        "Musical",
        "Noir",
        "Policial",
        "Psicológico",
        "Religioso",
        "Romance",
        "Romance Erótico",
        "Suspense",
        "Suspense Psicológico",
        "Terror",
        "Thriller",
        "Road Movie",
        "Super-herói",
        "Survival",
        "Teen",
        "True Crime"
    ]

    for name in categories:
        Category.objects.get_or_create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(insert_categories),
        migrations.RunPython(insert_versions),
    ]
