# Generated by Django 6.0.2 on 2026-02-19 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_filmcard_age_rating_id_filmcard_age_rating_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=20)),
                ('room', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='filmcard',
            old_name='created_at',
            new_name='modified_at',
        ),
        migrations.RemoveField(
            model_name='filmcard',
            name='edited_at',
        ),
        migrations.RemoveField(
            model_name='filmcard',
            name='edited_by_id',
        ),
        migrations.AddField(
            model_name='filmcard',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_films', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='filmcard',
            name='session_id',
            field=models.ManyToManyField(related_name='films_to_watch', to='api.session'),
        ),
    ]
