# Generated by Django 6.0.2 on 2026-03-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_session_day_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='day_number',
        ),
        migrations.AddField(
            model_name='session',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
