# Generated by Django 6.0.2 on 2026-02-19 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_session_rename_created_at_filmcard_modified_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filmcard',
            old_name='session_id',
            new_name='session',
        ),
    ]
