# Generated by Django 6.0.2 on 2026-03-02 12:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_session_day_number_session_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 3, 2, 12, 38, 25, 24041, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
