# Generated by Django 6.0.2 on 2026-02-21 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_session_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='film',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session_film', to='api.filmcard'),
        ),
    ]
