# Generated by Django 6.0.2 on 2026-02-27 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_category_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmcard',
            name='director',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filmcard',
            name='movie_cast',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
