# Generated by Django 6.0.3 on 2026-03-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_session_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmcard',
            name='ticket_url',
        ),
        migrations.AddField(
            model_name='session',
            name='ticket_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
