# Generated by Django 6.0.2 on 2026-02-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_session_id_filmcard_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmcard',
            name='session',
        ),
        migrations.RemoveField(
            model_name='session',
            name='date',
        ),
        migrations.RemoveField(
            model_name='session',
            name='time',
        ),
        migrations.AddField(
            model_name='session',
            name='days_list',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='session',
            name='film_list',
            field=models.ManyToManyField(related_name='sessions', to='api.filmcard'),
        ),
        migrations.AlterField(
            model_name='session',
            name='room',
            field=models.CharField(max_length=100),
        ),
    ]
