# Generated by Django 6.0.3 on 2026-03-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_filmcard_ticket_url_session_ticket_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmcard',
            name='banner_image',
            field=models.FileField(default=1, upload_to='banners/'),
            preserve_default=False,
        ),
    ]
