INSERT OR IGNORE INTO api_category 
(name, category_type_id, modified_by_id, modified_at) 
VALUES

-- AUDIO (1)
('Dolby Digital', 1, NULL, CURRENT_TIMESTAMP),
('Dolby Atmos', 1, NULL, CURRENT_TIMESTAMP),
('Dolby Surround 7.1', 1, NULL, CURRENT_TIMESTAMP),
('Dolby Surround 5.1', 1, NULL, CURRENT_TIMESTAMP),
('DTS', 1, NULL, CURRENT_TIMESTAMP),
('DTS:X', 1, NULL, CURRENT_TIMESTAMP),
('IMAX Sound', 1, NULL, CURRENT_TIMESTAMP),
('Auro 3D Audio', 1, NULL, CURRENT_TIMESTAMP),
('Som Estéreo', 1, NULL, CURRENT_TIMESTAMP),

-- VIDEO (2)
('2D', 2, NULL, CURRENT_TIMESTAMP),
('3D', 2, NULL, CURRENT_TIMESTAMP),
('IMAX', 2, NULL, CURRENT_TIMESTAMP),
('IMAX 3D', 2, NULL, CURRENT_TIMESTAMP),
('4DX', 2, NULL, CURRENT_TIMESTAMP),
('ScreenX', 2, NULL, CURRENT_TIMESTAMP),
('XD', 2, NULL, CURRENT_TIMESTAMP),
('Laser', 2, NULL, CURRENT_TIMESTAMP),
('HFR', 2, NULL, CURRENT_TIMESTAMP),
('HDR', 2, NULL, CURRENT_TIMESTAMP),
('Dolby Vision', 2, NULL, CURRENT_TIMESTAMP),
('Digital', 2, NULL, CURRENT_TIMESTAMP),

-- IDIOMA (3)
('Dublado', 3, NULL, CURRENT_TIMESTAMP),
('Legendado', 3, NULL, CURRENT_TIMESTAMP),
('Original', 3, NULL, CURRENT_TIMESTAMP),
('Português', 3, NULL, CURRENT_TIMESTAMP),
('Inglês', 3, NULL, CURRENT_TIMESTAMP),
('Espanhol', 3, NULL, CURRENT_TIMESTAMP),

-- ESPECIAL (4)
('VIP', 4, NULL, CURRENT_TIMESTAMP),
('Premium', 4, NULL, CURRENT_TIMESTAMP),
('Sala Gold', 4, NULL, CURRENT_TIMESTAMP),
('Sala Prime', 4, NULL, CURRENT_TIMESTAMP),
('Sala Platinum', 4, NULL, CURRENT_TIMESTAMP),
('D-BOX', 4, NULL, CURRENT_TIMESTAMP),
('Open Air', 4, NULL, CURRENT_TIMESTAMP),
('Sala Júnior', 4, NULL, CURRENT_TIMESTAMP),

-- OUTROS (5)
('Filme Nacional', 5, NULL, CURRENT_TIMESTAMP),
('Filme Internacional', 5, NULL, CURRENT_TIMESTAMP),

-- ACESSIBILIDADE (6)
('Libras', 6, NULL, CURRENT_TIMESTAMP),
('Audiodescrição', 6, NULL, CURRENT_TIMESTAMP),
('Legenda Descritiva', 6, NULL, CURRENT_TIMESTAMP),
('Sessão Azul', 6, NULL, CURRENT_TIMESTAMP);